[features]
seeds = true

[programs.mainnet]
coral_multisig = "863GdS1bjSSfyLSvR5JAWaqXTtsM8aR4c2vcK4vDLF8G"

[programs.devnet]
coral_multisig = "863GdS1bjSSfyLSvR5JAWaqXTtsM8aR4c2vcK4vDLF8G"

[programs.localnet]
coral_multisig = "863GdS1bjSSfyLSvR5JAWaqXTtsM8aR4c2vcK4vDLF8G"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
